name: Failures

on:
  push:

jobs:
  run-linters:
    runs-on: ubuntu-latest

    steps:

      - run: echo "ğŸ»"

      - run: echo "1. previous step failed"
        if: failure()

      - run: exit 1
        id: exit

      - run: echo "2. previous step failed"

      - run: echo "3. previous step failed"
        if: failure()

      - run: echo ${{ steps.exit.outcome}}
        if: failure()
